DROP TABLE IF EXISTS gold_user_value_profile;
CREATE TABLE IF NOT EXISTS gold_user_value_profile (
    `device_sk` VARCHAR(255),
    `geo_sk` VARCHAR(255),
    `user_sk` VARCHAR(255),
    `first_event_date` DATETIME,
    `last_event_date` DATETIME,
    `first_order_date` DATETIME,
    `last_order_date` DATETIME,
    `total_orders` BIGINT,
    `total_revenue` DECIMAL(20,2),
    `actual_revenue` DECIMAL(22,2),
    `expected_revenue` DECIMAL(22,2),
    `lost_revenue` DECIMAL(22,2),
    `primary_city` VARCHAR(255),
    `abs` INT,
    `aov` DECIMAL(10,2),
    `is_repeat_customer` BOOLEAN,
    `days_to_first_order` INT,
    `conversion_type` VARCHAR(255),
    `purchase_behavior` VARCHAR(255),
    `value_segment` VARCHAR(255),
    `first_name` VARCHAR(255),
    `last_name` VARCHAR(255),
    `email` VARCHAR(255),
    `phone` VARCHAR(255),
    `user_status` VARCHAR(255),
    `pref_language` VARCHAR(255),
    `latitude` DOUBLE,
    `longitude` DOUBLE,
    `device_family` VARCHAR(255),
    `os_family` VARCHAR(255),
    `browser_family` VARCHAR(255),
    `realized_ltv` DECIMAL(22,2),
    `potential_ltv` DECIMAL(23,2),
    `revenue_efficiency_score` DECIMAL(25,2),
    `churn_risk` VARCHAR(255) NOT NULL,
    `tenure_days` INT,
    `tenure_bucket` VARCHAR(255) NOT NULL,
    `purchase_tenure_days` INT,
    `purchase_tenure_bucket` VARCHAR(255) NOT NULL,
    `recency_days` INT,
    `r_score` INT NOT NULL,
    `f_score` INT NOT NULL,
    `m_score` INT NOT NULL,
    `rfm_score` VARCHAR(255) NOT NULL,
    `clv_rank` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`user_sk`),
    KEY `idx_gold_user_value_profile_geo_sk` (`geo_sk`),
    KEY `idx_gold_user_value_profile_device_sk` (`device_sk`),
    KEY `idx_gold_user_value_profile_value_segment` (`value_segment`),
    KEY `idx_gold_user_value_profile_clv_rank` (`clv_rank`),
    KEY `idx_gold_user_value_profile_churn_risk` (`churn_risk`),
    KEY `idx_gold_user_value_profile_purchase_behavior` (`purchase_behavior`),
    KEY `idx_gold_user_value_profile_recency_days` (`recency_days`),
    KEY `idx_gold_user_value_profile_last_order_date` (`last_order_date`),
    KEY `idx_gold_user_value_profile_realized_ltv` (`realized_ltv`),
    KEY `idx_gold_user_value_profile_r_score` (`r_score`),
    KEY `idx_gold_user_value_profile_f_score` (`f_score`),
    KEY `idx_gold_user_value_profile_m_score` (`m_score`)
) ENGINE=InnoDB;